services:
  server:
    build: ./server
    ports:
      - '0.0.0.0:3000:3000'
      - '0.0.0.0:3443:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    container_name: server
  client:
    build: ./client
    ports:
      - '0.0.0.0:8080:8080'
    volumes:
      - ./client:/app
      - /app/node_modules
    container_name: client
