services:
  server:
    build: ./server
    ports:
      - '3000:3000'
      - '3443:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    container_name: server
    environment:
      - NODE_ENV=development
    networks:
      - transcendence-network
  client:
    build: ./client
    ports:
      - '8080:8080'
    volumes:
      - ./client:/app
      - /app/node_modules
    container_name: client
    environment:
      - NODE_ENV=development
    networks:
      - transcendence-network
    depends_on:
      - server

networks:
  transcendence-network:
    driver: bridge
