services:
    server:
        build: ./server
        ports:
            - '3000:3000'
        volumes:
            - ./server:/app
            - /app/node_modules

    client:
        build: ./client
        ports:
            - '8080:80'
        volumes:
            - ./client:/usr/share/nginx/html
        restart: always
